apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener:  pipeline-test-listener-interceptor
  name: pipeline-test-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-pipeline-test-listener-interceptor
