apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-test-pr-
spec:
  params:
  - name: git-url
    value: https://github.com/marrober/pipelineBuildExample.git
  - name: git-revision
    value: main
  pipelineRef:
    name: pipeline-test
  workspaces:
  - name: resources
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
