kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: liberty-rest
    app.kubernetes.io/part-of: liberty
  name: liberty-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liberty-rest
  template:
    metadata:
      labels:
        app: liberty-rest
      annotations:
    spec:
      containers:
      - env:
        image: default-route-openshift-image-registry.apps.cluster-3db0.3db0.sandbox1706.opentlc.com/liberty-rest/liberty-rest-app:latest
        imagePullPolicy: Always
        name: liberty-rest
        ports:
        - containerPort: 9080
          name: http
          protocol: TCP
