apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    p, role:org-admin, logs, get, *, allow
    p, role:org-admin, exec, create, */*, allow
#      u/g/r, resource,                  action, object
    p, user1, liberty-rest/pipeline-app, get, *, allow
    p, user1, liberty-rest/pipeline-app, sync, *, allow
    p, user1, liberty-rest/pipeline-app, override, *, allow
    p, user1, clusters, get, *, allow
    p, user1, repositories, get, *, allow
    p, user1, repositories, create, *, allow
    p, user1, repositories, update, *, allow
    p, user1, repositories, delete, *, allow
    p, user1, logs, get, *, allow
    p, user1, exec, create, */*, allow

#    g, your-github-org:your-team, role:org-admin